### ISSUE TITLE
Columns connect if column text length matches column width

### ISSUE THREAD

**Issue by briandowns** [fatih/images#21] opened 2015-06-09 02:10 UTC
```bash
AWS Region: us-west-2 (2 images):
    Name	ID		State		Tags
[1] tester	ami-3b172f0b	available	[]
[2] test-image-2ami-63172f53	pending		[]
```

```bash
AWS Region: us-west-2 (5 images):
    Name		ID		State															Tags
[1] tester		ami-3b172f0b	available														[]
[2] test-image-2	ami-63172f53	available														[]
[3] testing-images-44	ami-6b172f5b	failed (Server.InternalError:The instance is not yet ready to schedule a bundling operation. You may try again shortly)	[]
[4] test-image-9999	ami-57172f67	available														[]
[5] aqswdefrgthyjukilopmami-07093137	pending
```

Any thoughts on possibly using github.com/olekukonko/tablewriter ?

**Comment by fatih** [comment] 2015-06-09 10:19
Hi @briandowns. Thanks for the report. I'm using already a tabwriter. It seems I need to adjust it for very long names. Let me check it. I'm aware of tablewriter, however I'm not keen to add new dependencies. If tabwriter is not enough for us, I'm going to look at tablewriter.

**Comment by briandowns** [comment] 2015-06-09 12:31
I figured I'd just through the idea out there for tablewriter.  I like the tabwriter implementation though.  I tried fixing the bug last night but none of the changes I made were reflected once images was rebuilt.  I'm curious what I was doing wrong.  I was editing the provider/aws/images.go and adjust line 38.  Any help with that would be greatly appreciated.

**Comment by fatih** [comment] 2015-06-09 12:37
Actually all you need is to do a `make build`. It will create a binary inside `bin/` folder. So `bin/images`. Does that not work for you ? `images -version` for example should print `dev` if you build it.

Another solution would be to run it with the `godep` tool, but I don't encourage it. Example:

```
godep go run main.go list --providers aws
```

Try `make build`. We should fix it if it doesn't work for you.

**Comment by briandowns** [comment] 2015-06-09 12:42
That's really strange.  That's what I was doing.  I'm probably doing something else wrong.  I'll keep messing with it.  Thanks!

**Comment by fatih** [comment] 2015-06-11 20:20
I somehow couldn't reproduce it :/  Here is an example from gce (note that they all share the same tabwriter):

![image](https://cloud.githubusercontent.com/assets/438920/8117380/5800ed6e-1090-11e5-84b6-214f1db6494d.png)

What exactly was your fix? Or can you give more detail how to reproduce it ?

**Comment by briandowns** [comment] 2015-06-11 20:45
My fix was to just adjust the tabwriter creation parameters but couldn't get it going correctly when building. My example is from AWS. 

Brian

**Comment by fatih** [comment] 2015-06-11 23:11
I've pushed a fix to master which adds a padding. It never concatenates now rows.

**Closed** 2015-06-11 23:11 UTC
Labels: bug

**Comment by briandowns** [comment] 2015-06-12 00:01
Confirmed.  Looks great.  Thanks!
